name: "🚀 Publish Server Container"

on:
  push:
    branches:
      - "master"
    paths:
      - "server/**"
  # TODO: remove after testing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'master') }}

permissions:
  # contents: write # due to GiNo-KeVa TODO: move to gino-keva job
  packages: write # to publish to GHCR.io

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
      imgTags: ${{ steps.imageFacts.outputs.IMG_TAGS }}
      imgCreated: ${{ steps.imageFacts.outputs.IMG_CREATED }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu
          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}

      - name: "Gather Image Facts"
        id: imageFacts
        run: |-
          set -exu
          APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)

          if [[ "${{ github.ref }}" =~ master ]]; then
            echo "IMG_TAGS=unstable ${APP_VERSION}" >> ${GITHUB_OUTPUT}
          else
            echo "IMG_TAGS=latest ${APP_VERSION}" >> ${GITHUB_OUTPUT}
          fi

          echo "IMG_CREATED=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")" >> ${GITHUB_OUTPUT}


  buildContainer:
    uses: ./.github/workflows/_meta-containerBuild.yaml
    needs:
      - gatherFacts
    with:
      codeRepository: ${{ needs.gatherFacts.outputs.appRepo }}
      codeRepositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}
      containerSpec: server
      imageName: jellyfin-server
      imageTags: ${{ needs.gatherFacts.outputs.imgTags }}
      imageLabels: |-
        org.opencontainers.image.created=${{ needs.gatherFacts.outputs.imgCreated }}
        org.opencontainers.image.version=${{ needs.gatherFacts.outputs.appVersion }}
        org.opencontainers.image.revision=${{ needs.gatherFacts.outputs.appGitSha }}
        org.opencontainers.image.source=https://github.com/${{ needs.gatherFacts.outputs.appRepo }}
      containerfile: Containerfile.debian
    secrets:
      ghc_usr: ${{ github.actor }}
      ghc_tkn: ${{ github.token }}

  # buildSlimContainer:

  # publishGhRelease

  # bumpGitNotes
