name: "🚀 Publish Server Container"

on:
  push:
    branches:
      - "master"
      - "release-*"
    paths:
      - "server/**"
      - ".github/workflows/build-server.yaml"
      - ".github/workflows/_meta-containerBuild.yaml"
  # TODO: remove after testing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'master') }}

permissions:
  contents: read
  # contents: write # due to GiNo-KeVa TODO: move to gino-keva job

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu
          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}


  buildContainer:
    uses: ./.github/workflows/_meta-containerBuild.yaml
    needs:
      - gatherFacts
    permissions:
      packages: write # to publish to GHCR.io
    with:
      codeRepository: ${{ needs.gatherFacts.outputs.appRepo }}
      codeRepositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}
      containerSpec: server
      imageName: jellyfin-server
      imageTag: ${{ needs.gatherFacts.outputs.appVersion }}
      imageLabels: |-
        org.opencontainers.image.vendor=Jellyfin project
        org.opencontainers.image.title=Jellyfin - The Free Software Media System - Server
        org.opencontainers.image.description=Official Jellyfin server container image
        org.opencontainers.image.url=https://jellyfin.org
        org.opencontainers.image.licenses=GPL-2.0
        org.opencontainers.image.version=${{ needs.gatherFacts.outputs.appVersion }}
        org.opencontainers.image.revision=${{ needs.gatherFacts.outputs.appGitSha }}
        org.opencontainers.image.source=https://github.com/${{ needs.gatherFacts.outputs.appRepo }}
      containerfile: Containerfile.debian
      publishImage: true # for now
    secrets:
      ghc_usr: ${{ github.actor }}
      ghc_tkn: ${{ secrets.GITHUB_TOKEN }}

  # publishGhRelease

  # bumpGitNotes
