name: "🚀 Publish standalone Web-Client container"

on:
  push:
    branches:
      - "master"
      - "release-*"
    paths:
      - "web-client/**"
  # TODO: remove after testing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'master') }}

permissions:
  contents: write # due to GiNo-KeVa
  packages: write # to publish to GHCR.io

jobs:
  buildContainer:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install qemu dependency"
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: "Gather Variables"
        run: |-
          set -exu
          APP_VERSION=$(yq '.version' web-client/metaValues.yaml)
          APP_GIT_SHA=$(yq '.gitSha' web-client/metaValues.yaml)

          echo "IMG_CREATED=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")" >> $GITHUB_ENV
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "APP_GIT_SHA=${APP_GIT_SHA}" >> $GITHUB_ENV

          if [[ "${{ github.ref }}" =~ master ]]; then
            echo "CONTAINER_TAGS=latest ${APP_VERSION}" >> $GITHUB_ENV
          else
            echo "CONTAINER_TAGS=unstable ${APP_VERSION}" >> $GITHUB_ENV
          fi

      - name: "Download Incremental Workflow Artifact"
        if: ${{ contains(github.ref, 'master') }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.JF_BOT_TOKEN }}
          repo: ${{ github.repository_owner }}/jellyfin-web-sandbox
          workflow: ci-build.yaml
          name: jellyfin-web_production
          commit: ${{ env.APP_GIT_SHA }}

      - name: "Download Release Artifact"
        if: ${{ contains(github.ref, 'release') }}
        run: |-
          set -exu
          curl -fsSLO --compressed https://github.com/${{ github.repository_owner }}/jellyfin-web-sandbox/releases/download/v${{ env.APP_VERSION }}/jellyfin-web_portable.tar.gz

      - name: "Extract Web-Client Tar"
        run: |-
          mkdir container/jellyfin-web
          tar -xzf jellyfin-web_portable.tar.gz -C container/jellyfin-web

      - name: "Build Container Image"
        id: containerBuild
        uses: redhat-actions/buildah-build@v2.10
        with:
          image: jellyfin-web
          oci: true
          tags: ${{ env.CONTAINER_TAGS }}
          labels: |-
            org.opencontainers.image.created=${{ env.IMG_CREATED }}
            org.opencontainers.image.version=${{ env.APP_VERSION }}
            org.opencontainers.image.revision=${{ env.APP_GIT_SHA }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/jellyfin-web-sandbox
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7
          context: container
          containerfiles: |-
            web-client/Containerfile.alpine

      - name: "Push Container Image to ghcr.io"
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.containerBuild.outputs.image }}
          tags: ${{ steps.containerBuild.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
