name: "🚀 Publish Server Container"

on:
  push:
    branches:
      - "master"
      - "release-*"
    paths:
      - "server/**"
      - ".github/workflows/build-server.yaml"
      - ".github/workflows/_meta-containerBuild.yaml"
  # TODO: remove after testing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'master') }}

permissions:
  contents: read
  # contents: write # due to GiNo-KeVa TODO: move to gino-keva job

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
      imgTags: ${{ steps.imageFacts.outputs.tags }}
      imgLabels: ${{ steps.imageFacts.outputs.labels }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu
          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}

      - name: "Gather Container Image Facts"
        id: imageFacts
        uses: docker/metadata-action@v4
        with:
          # docker.io/jellyfin/jellyfin-server
          # quay.io/jellyfin/jellyfin-server
          images: |-
            ghcr.io/${{ github.repository_owner }}/jellyfin-server
          tags: |-
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/heads/release-') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/heads/release-') }}
            type=raw,value=${{ steps.variables.outputs.APP_VERSION }},enable=${{ ! startsWith(github.ref, 'refs/heads/release-') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/release-') }}
            type=raw,value=unstable,enable=${{ ! startsWith(github.ref, 'refs/heads/release-') }}
          labels: |-
            org.opencontainers.image.version=${{ steps.variables.outputs.APP_VERSION }}
            org.opencontainers.image.revision=${{ steps.variables.outputs.APP_GIT_SHA }}
            org.opencontainers.image.source=https://github.com/${{ steps.variables.outputs.APP_REPO }}


  buildContainer:
    uses: ./.github/workflows/_meta-containerBuild.yaml
    needs:
      - gatherFacts
    permissions:
      packages: write # to publish to GHCR.io
    with:
      codeRepository: ${{ needs.gatherFacts.outputs.appRepo }}
      codeRepositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}
      containerSpec: server
      imageTags: ${{ needs.gatherFacts.outputs.imgTags }}
      imageLabels: ${{ needs.gatherFacts.outputs.imgLabels }}
      containerfile: Containerfile.debian
      publishImage: true # for now
    secrets:
      ghc_usr: ${{ github.actor }}
      ghc_tkn: ${{ secrets.GITHUB_TOKEN }}

  # publishGhRelease

  # bumpGitNotes
